name: Build Docs
on:
  push:
    branches:
      - master
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build docs
        run: npm run compodoc